id: 5df75edc75474d648217996b151d4c44
initial_creation_type: ocr
source_metadata:
  volumes:
    f442ba8df0794ff985a3f32c28638c3c:
      base_file: v064.txt
      image_group_id: I1PD95910
      title: ལྟུང་བ་བཤགས་པའི་ཆོ་ག།
      total_pages: 1498
      volume_number: 65
