id: 5df75edc75474d648217996b151d4c44
initial_creation_type: ocr
source_metadata:
  volumes:
    0ed7d9cb4f044875878a107942d27fb7:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: ལྟུང་བ་བཤགས་པའི་ཆོ་ག།
      total_pages: 1498
      volume_number: 65
